name: Continuous Integration
on: 
  - pull_request
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
        working-directory: ./fooling-around-app
      - name: Build
        run: yarn build
        working-directory: ./fooling-around-app
      - name: Test
        run: yarn test --watchAll=false
        working-directory: ./fooling-around-app