name: Continuous Deployment
defaults:
  run:
    working-directory: ./fooling-around-app
on:
  push:
    branches:
      - main
      - dev
jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    env:
      SOURCE_DIR: "build/"
      AWS_REGION: "us-east-2"
      AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Deploy staging
        if: github.ref == 'refs/heads/dev'
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.STAGING_AWS_S3_BUCKET }}
      - name: Deploy production
        if: github.ref == 'refs/heads/main'
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.PRODUCTION_AWS_S3_BUCKET }}